[tool.poetry]
package-mode = false
name = "romm"
version = "0.0.1"
description = "A beautiful, powerful, self-hosted rom manager"
license = "GNU GPLv3"
repository = "https://github.com/rommapp/romm"
authors = [
    "Zurdi <https://github.com/zurdi15/>",
    "Georges-Antoine Assi <contact@me.gantoine.com>",
]

[tool.poetry.dependencies]
python = "^3.11"
requests = "2.31.0"
fastapi = "0.110.0"
uvicorn = "0.29.0"
gunicorn = "22.0.0"
websockets = "12.0"
python-socketio = "5.11.1"
SQLAlchemy = {extras = ["mypy"], version = "^2.0.28"}
alembic = "1.13.1"
PyYAML = "6.0.1"
Unidecode = "1.3.8"
emoji = "2.10.1"
python-dotenv = "1.0.1"
fastapi-pagination = "^0.12.19"
sqlakeyset = "^2.0.1708907391"
pydash = "^7.0.7"
mariadb = "1.1.10"
rq = "^1.16.1"
aioredis = "^2.0.1"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
itsdangerous = "^2.1.2"
stream-zip = "^0.0.71"
rq-scheduler = "^0.13.1"
starlette-csrf = "^3.0.0"
httpx = "^0.27.0"
python-multipart = "^0.0.9"
watchdog = "^4.0.0"
fakeredis = "^2.21.3"
yarl = "^1.9.4"
joserfc = "^0.9.0"
pillow = "^10.3.0"
mypy = "^1.10.0"
types-passlib = "^1.7.7.20240327"
types-redis = "^4.6.0.20240425"
types-pyyaml = "^6.0.12.20240311"
types-requests = "^2.31.0.20240406"
sqlalchemy-stubs = "^0.4"

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
pytest-env = "^1.1.3"
pytest-vcr = "^1.0.2"
pytest-mock = "^3.12.0"
pytest-asyncio = "^0.23.5"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"

[tool.mypy]
ignore_missing_imports = true
strict = false

[[tool.mypy.overrides]]
module = [
    "endpoints.tests.*",
    "handler.auth.tests.*",
    "handler.filesystem.tests.*",
    "handler.tests.*",
    "models.tests.*",
]
ignore_errors = true
